//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArqueoCaja
    {
        public int ArqueoCajaId { get; set; }
        public Nullable<int> IdDenominacionMoneda { get; set; }
        public int Cantidad { get; set; }
        public Nullable<int> CajaAperturaId { get; set; }
    
        public virtual CajaApertura CajaApertura { get; set; }
        public virtual DenominacionMoneda DenominacionMoneda { get; set; }
    }
}
