//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiento
    {
        public Asiento()
        {
            this.AsientoDetalle = new HashSet<AsientoDetalle>();
        }
    
        public int AsientoId { get; set; }
        public string Modulo { get; set; }
        public System.DateTime FechaAsiento { get; set; }
        public string NumeroAsiento { get; set; }
        public string Glosa { get; set; }
        public decimal ValorCambio { get; set; }
        public string CodDocumento { get; set; }
        public int ContratoId { get; set; }
    
        public virtual Documento Documento { get; set; }
        public virtual ContratoEmpresaAfiliado ContratoEmpresaAfiliado { get; set; }
        public virtual ICollection<AsientoDetalle> AsientoDetalle { get; set; }
    }
}
