//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsientoDetalle
    {
        public int AsientoDetalleId { get; set; }
        public decimal Debe { get; set; }
        public decimal Haber { get; set; }
        public int Tipo { get; set; }
        public decimal DebeDolar { get; set; }
        public decimal HaberDolar { get; set; }
        public int AsientoId { get; set; }
        public string CodigoCuenta { get; set; }
    
        public virtual Asiento Asiento { get; set; }
        public virtual PlanContable PlanContable { get; set; }
    }
}
