//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CajaApertura
    {
        public CajaApertura()
        {
            this.ArqueoCaja = new HashSet<ArqueoCaja>();
            this.CambioMoneda = new HashSet<CambioMoneda>();
            this.DepositoPrestamo = new HashSet<DepositoPrestamo>();
            this.MovimientoFondos = new HashSet<MovimientoFondos>();
            this.ReciboCaja = new HashSet<ReciboCaja>();
            this.Transferencia = new HashSet<Transferencia>();
        }
    
        public int CajaAperturaId { get; set; }
        public Nullable<int> CajaId { get; set; }
        public Nullable<System.DateTime> FechaTrabajo { get; set; }
        public string UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaHoraApertura { get; set; }
        public Nullable<decimal> MontoAperturaS { get; set; }
        public Nullable<decimal> MontoAperturaD { get; set; }
        public Nullable<decimal> MontoCierreS { get; set; }
        public Nullable<decimal> MontoCierreD { get; set; }
        public Nullable<System.DateTime> FechaHoraArqueo { get; set; }
        public bool FlagCerrado { get; set; }
        public string Observacion { get; set; }
    
        public virtual ICollection<ArqueoCaja> ArqueoCaja { get; set; }
        public virtual Caja Caja { get; set; }
        public virtual CajaApertura CajaApertura1 { get; set; }
        public virtual CajaApertura CajaApertura2 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<CambioMoneda> CambioMoneda { get; set; }
        public virtual ICollection<DepositoPrestamo> DepositoPrestamo { get; set; }
        public virtual ICollection<MovimientoFondos> MovimientoFondos { get; set; }
        public virtual ICollection<ReciboCaja> ReciboCaja { get; set; }
        public virtual ICollection<Transferencia> Transferencia { get; set; }
    }
}
