//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public Caja()
        {
            this.CajaApertura = new HashSet<CajaApertura>();
        }
    
        public int CajaId { get; set; }
        public string Nombre { get; set; }
        public string Contrasenia { get; set; }
        public bool Estado { get; set; }
        public string CodigoCuenta { get; set; }
    
        public virtual PlanContable PlanContable { get; set; }
        public virtual ICollection<CajaApertura> CajaApertura { get; set; }
    }
}
