//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioMoneda
    {
        public int NumeroDocumento { get; set; }
        public int MonedaOrigenId { get; set; }
        public int MonedaDestinoId { get; set; }
        public string RazonSocial { get; set; }
        public decimal Importe { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<bool> FlagImpreso { get; set; }
        public Nullable<int> CajaAperturaId { get; set; }
        public string UsuarioAnulado { get; set; }
        public Nullable<System.DateTime> FechaHoraAnulacion { get; set; }
        public Nullable<int> ConceptoId { get; set; }
    
        public virtual CajaApertura CajaApertura { get; set; }
        public virtual Concepto Concepto { get; set; }
        public virtual TipoCambio TipoCambio { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Moneda Moneda1 { get; set; }
    }
}
