//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComprobanteCompra
    {
        public ComprobanteCompra()
        {
            this.ReciboCaja = new HashSet<ReciboCaja>();
        }
    
        public int ComprobanteCompraId { get; set; }
        public string RUC { get; set; }
        public string RazonSocial { get; set; }
        public Nullable<int> NumeroDocumento { get; set; }
        public Nullable<int> NumeroSerie { get; set; }
    
        public virtual ICollection<ReciboCaja> ReciboCaja { get; set; }
    }
}
