//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comprobante
    {
        public Comprobante()
        {
            this.Documento = new HashSet<Documento>();
            this.Serie = new HashSet<Serie>();
        }
    
        public string CodComprobante { get; set; }
        public string NombreComprobante { get; set; }
        public bool CreditoFiscal { get; set; }
    
        public virtual ICollection<Documento> Documento { get; set; }
        public virtual ICollection<Serie> Serie { get; set; }
    }
}
