//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public Concepto()
        {
            this.CambioMoneda = new HashSet<CambioMoneda>();
            this.DepositoPrestamo = new HashSet<DepositoPrestamo>();
            this.Transferencia = new HashSet<Transferencia>();
            this.MovimientoFondos = new HashSet<MovimientoFondos>();
            this.ReciboCaja = new HashSet<ReciboCaja>();
        }
    
        public int ConceptoId { get; set; }
        public string Nombre { get; set; }
        public string CodigoCuenta { get; set; }
    
        public virtual ICollection<CambioMoneda> CambioMoneda { get; set; }
        public virtual PlanContable PlanContable { get; set; }
        public virtual ICollection<DepositoPrestamo> DepositoPrestamo { get; set; }
        public virtual ICollection<Transferencia> Transferencia { get; set; }
        public virtual ICollection<MovimientoFondos> MovimientoFondos { get; set; }
        public virtual ICollection<ReciboCaja> ReciboCaja { get; set; }
    }
}
