//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContratoEmpresaAfiliado
    {
        public ContratoEmpresaAfiliado()
        {
            this.Asiento = new HashSet<Asiento>();
        }
    
        public int ContratoId { get; set; }
        public string CodigoOficina { get; set; }
        public int EmpresaAfiliadaId { get; set; }
        public int ComisionDTDirecto { get; set; }
        public int ComisionDTAfiliado { get; set; }
        public decimal Garantia { get; set; }
        public System.DateTime FechaContrato { get; set; }
        public bool Estado { get; set; }
        public bool SujetoVariacionArreglo { get; set; }
    
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual Oficina Oficina { get; set; }
        public virtual EmpresaAfiliada EmpresaAfiliada { get; set; }
    }
}
