//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaBancaria
    {
        public CuentaBancaria()
        {
            this.MovimientoFondos = new HashSet<MovimientoFondos>();
        }
    
        public int NumeroCuentaBanco { get; set; }
        public string NombreCuentaBancaria { get; set; }
        public int TipoCuenta { get; set; }
        public int Estado { get; set; }
        public string CodigoPersona { get; set; }
        public int EntidadId { get; set; }
        public string CodigoCuenta { get; set; }
        public int MonedaId { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual PlanContable PlanContable { get; set; }
        public virtual EntidadFinanciera EntidadFinanciera { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual ICollection<MovimientoFondos> MovimientoFondos { get; set; }
    }
}
