//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DenominacionMoneda
    {
        public DenominacionMoneda()
        {
            this.ArqueoCaja = new HashSet<ArqueoCaja>();
        }
    
        public int DenominacionMonedaId { get; set; }
        public decimal Valor { get; set; }
        public string Denominacion { get; set; }
        public Nullable<int> MonedaId { get; set; }
    
        public virtual ICollection<ArqueoCaja> ArqueoCaja { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
