//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepositoPrestamo
    {
        public int NumeroDocumento { get; set; }
        public System.DateTime FechaHoraTransaccion { get; set; }
        public Nullable<int> TipoOperacion { get; set; }
        public Nullable<int> MonedaId { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<System.DateTime> FechaHoraAnulacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public string CodigoPersona { get; set; }
        public Nullable<int> CajaAperturaId { get; set; }
        public Nullable<int> ConceptoId { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> FlagImpreso { get; set; }
        public Nullable<decimal> Interes { get; set; }
    
        public virtual CajaApertura CajaApertura { get; set; }
        public virtual Concepto Concepto { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual TipoCambio TipoCambio { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
