//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documento
    {
        public Documento()
        {
            this.Asiento = new HashSet<Asiento>();
            this.Transferencia = new HashSet<Transferencia>();
            this.MovimientoFondos = new HashSet<MovimientoFondos>();
            this.ReciboCaja = new HashSet<ReciboCaja>();
        }
    
        public string CodDocumento { get; set; }
        public string CodComprobante { get; set; }
        public string NombreDocumento { get; set; }
        public string ProcesoAsociado { get; set; }
        public string FormatoImpresion { get; set; }
        public int PrimerDocumento { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<Asiento> Asiento { get; set; }
        public virtual Comprobante Comprobante { get; set; }
        public virtual ICollection<Transferencia> Transferencia { get; set; }
        public virtual ICollection<MovimientoFondos> MovimientoFondos { get; set; }
        public virtual ICollection<ReciboCaja> ReciboCaja { get; set; }
    }
}
