//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaAfiliada
    {
        public EmpresaAfiliada()
        {
            this.ContratoEmpresaAfiliado = new HashSet<ContratoEmpresaAfiliado>();
        }
    
        public int EmpresaAfiliadaId { get; set; }
        public string CodigoPersona { get; set; }
    
        public virtual ICollection<ContratoEmpresaAfiliado> ContratoEmpresaAfiliado { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
