//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadFinanciera
    {
        public EntidadFinanciera()
        {
            this.Banco = new HashSet<Banco>();
            this.CuentaBancaria = new HashSet<CuentaBancaria>();
        }
    
        public int EntidadId { get; set; }
        public string CodEntidad { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Banco> Banco { get; set; }
        public virtual ICollection<CuentaBancaria> CuentaBancaria { get; set; }
    }
}
