//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moneda
    {
        public Moneda()
        {
            this.CambioMoneda = new HashSet<CambioMoneda>();
            this.CambioMoneda1 = new HashSet<CambioMoneda>();
            this.CuentaBancaria = new HashSet<CuentaBancaria>();
            this.DenominacionMoneda = new HashSet<DenominacionMoneda>();
            this.DepositoPrestamo = new HashSet<DepositoPrestamo>();
            this.MovimientoFondos = new HashSet<MovimientoFondos>();
            this.ReciboCaja = new HashSet<ReciboCaja>();
            this.Transferencia = new HashSet<Transferencia>();
        }
    
        public int MonedaId { get; set; }
        public string Nombre { get; set; }
        public string Simbolo { get; set; }
        public string Abreviatura { get; set; }
        public string Referencia { get; set; }
        public bool EsNacional { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<CambioMoneda> CambioMoneda { get; set; }
        public virtual ICollection<CambioMoneda> CambioMoneda1 { get; set; }
        public virtual ICollection<CuentaBancaria> CuentaBancaria { get; set; }
        public virtual ICollection<DenominacionMoneda> DenominacionMoneda { get; set; }
        public virtual ICollection<DepositoPrestamo> DepositoPrestamo { get; set; }
        public virtual ICollection<MovimientoFondos> MovimientoFondos { get; set; }
        public virtual ICollection<ReciboCaja> ReciboCaja { get; set; }
        public virtual ICollection<Transferencia> Transferencia { get; set; }
    }
}
