//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovimientoFondos
    {
        public int NumeroDocumento { get; set; }
        public string CodDocumento { get; set; }
        public Nullable<int> MonedaId { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string OficinaIdProcedencia { get; set; }
        public string OficinaIdDestino { get; set; }
        public string CodigoPersona { get; set; }
        public Nullable<int> BancoId { get; set; }
        public Nullable<int> NumeroCuentaBanco { get; set; }
        public string CodigoVoucher { get; set; }
        public string NumeroOperacion { get; set; }
        public Nullable<int> CajaAperturaId { get; set; }
        public Nullable<System.DateTime> FechaHoraAnulacion { get; set; }
        public Nullable<int> Estado { get; set; }
        public string UsuarioAnulacion { get; set; }
        public Nullable<int> ConceptoId { get; set; }
        public Nullable<int> TipoMovimiento { get; set; }
        public Nullable<System.DateTime> FechaHoraTransaccion { get; set; }
        public Nullable<System.DateTime> FechaHoraDescargo { get; set; }
        public bool FlagImpreso { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual CajaApertura CajaApertura { get; set; }
        public virtual Concepto Concepto { get; set; }
        public virtual CuentaBancaria CuentaBancaria { get; set; }
        public virtual Documento Documento { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Oficina Oficina { get; set; }
        public virtual Oficina Oficina1 { get; set; }
    }
}
