//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public Persona()
        {
            this.CuentaBancaria = new HashSet<CuentaBancaria>();
            this.DepositoPrestamo = new HashSet<DepositoPrestamo>();
            this.EmpresaAfiliada = new HashSet<EmpresaAfiliada>();
            this.MovimientoFondos = new HashSet<MovimientoFondos>();
            this.PersonaDetalle = new HashSet<PersonaDetalle>();
            this.ReciboCaja = new HashSet<ReciboCaja>();
            this.Transferencia = new HashSet<Transferencia>();
            this.Transferencia1 = new HashSet<Transferencia>();
        }
    
        public string CodigoPersona { get; set; }
        public int TipoPersona { get; set; }
        public string RazonSocial { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public int TipoDocumentoId { get; set; }
        public string NumeroDocumento { get; set; }
        public string CodigoUbigeo { get; set; }
        public string DireccionDomicilio { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Email { get; set; }
        public string Web { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<CuentaBancaria> CuentaBancaria { get; set; }
        public virtual ICollection<DepositoPrestamo> DepositoPrestamo { get; set; }
        public virtual ICollection<EmpresaAfiliada> EmpresaAfiliada { get; set; }
        public virtual ICollection<MovimientoFondos> MovimientoFondos { get; set; }
        public virtual TipoDocumentoIdentidad TipoDocumentoIdentidad { get; set; }
        public virtual ICollection<PersonaDetalle> PersonaDetalle { get; set; }
        public virtual ICollection<ReciboCaja> ReciboCaja { get; set; }
        public virtual ICollection<Transferencia> Transferencia { get; set; }
        public virtual ICollection<Transferencia> Transferencia1 { get; set; }
    }
}
