//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanContable
    {
        public PlanContable()
        {
            this.AsientoDetalle = new HashSet<AsientoDetalle>();
            this.Caja = new HashSet<Caja>();
            this.Concepto = new HashSet<Concepto>();
            this.CuentaBancaria = new HashSet<CuentaBancaria>();
        }
    
        public string CodigoCuenta { get; set; }
        public string Denominacion { get; set; }
        public string Naturaleza { get; set; }
        public string TipoCuenta { get; set; }
        public string Estructura { get; set; }
        public Nullable<int> Nivel { get; set; }
        public string CodigoCuentaPadre { get; set; }
    
        public virtual ICollection<AsientoDetalle> AsientoDetalle { get; set; }
        public virtual ICollection<Caja> Caja { get; set; }
        public virtual ICollection<Concepto> Concepto { get; set; }
        public virtual ICollection<CuentaBancaria> CuentaBancaria { get; set; }
    }
}
