//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Serie
    {
        public int SerieId { get; set; }
        public string CodComprobante { get; set; }
        public int NumeroSerie { get; set; }
        public int NumeroDigitos { get; set; }
        public bool CierreSerie { get; set; }
        public string CodigoOficina { get; set; }
    
        public virtual Comprobante Comprobante { get; set; }
        public virtual Oficina Oficina { get; set; }
    }
}
