//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDocumentoIdentidad
    {
        public TipoDocumentoIdentidad()
        {
            this.Persona = new HashSet<Persona>();
        }
    
        public int TipoDocumentoId { get; set; }
        public string Abreviatura { get; set; }
        public string Denominacion { get; set; }
    
        public virtual ICollection<Persona> Persona { get; set; }
    }
}
