//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transferencia
    {
        public int TransferenciaId { get; set; }
        public int NumeroDocumento { get; set; }
        public string CodDocumento { get; set; }
        public string OficinaIdProcedencia { get; set; }
        public string OficinaIdDestino { get; set; }
        public string PersonaIdSolicitante { get; set; }
        public string PersonaIdBeneficiario { get; set; }
        public Nullable<System.DateTime> FechaHoraTransferencia { get; set; }
        public int MonedaId { get; set; }
        public decimal Importe { get; set; }
        public decimal DerechoTransferencia { get; set; }
        public decimal DerechoTransferenciaArreglo { get; set; }
        public string ObsTransferencia { get; set; }
        public Nullable<System.DateTime> FechaHoraAnulacion { get; set; }
        public string UsuarioAnulacion { get; set; }
        public Nullable<int> BancoId { get; set; }
        public string NumeroCuentaBanco { get; set; }
        public Nullable<decimal> ComisionBancaria { get; set; }
        public Nullable<int> TipoOperacionBancaria { get; set; }
        public string CodigoOperacion { get; set; }
        public Nullable<int> EstadoOperacionBancaria { get; set; }
        public string MotivoAnulacion { get; set; }
        public Nullable<System.DateTime> FechaHoraPago { get; set; }
        public string CodDocumentoPago { get; set; }
        public Nullable<int> NroDocumentoPago { get; set; }
        public string ObsPagoTransferencia { get; set; }
        public Nullable<int> Estado { get; set; }
        public Nullable<bool> FlagImpreso { get; set; }
        public Nullable<int> CajaAperturaId { get; set; }
        public Nullable<int> TipoTransaccion { get; set; }
        public Nullable<int> ConceptoId { get; set; }
        public string CodigoSeguridad { get; set; }
        public bool FlagArregloCuenta { get; set; }
        public bool FlagChequeo { get; set; }
        public Nullable<System.DateTime> FechaHoraChequeo { get; set; }
        public string UsuarioChequeo { get; set; }
        public string UsuarioArregloCuenta { get; set; }
    
        public virtual Banco Banco { get; set; }
        public virtual CajaApertura CajaApertura { get; set; }
        public virtual Concepto Concepto { get; set; }
        public virtual Documento Documento { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Oficina Oficina { get; set; }
        public virtual Oficina Oficina1 { get; set; }
        public virtual Persona Persona { get; set; }
        public virtual Persona Persona1 { get; set; }
    }
}
