//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mega.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Accesos = new HashSet<Accesos>();
            this.CajaApertura = new HashSet<CajaApertura>();
        }
    
        public string UsuarioId { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<Accesos> Accesos { get; set; }
        public virtual ICollection<CajaApertura> CajaApertura { get; set; }
    }
}
